platform :ios, '9.0'
target '动态' do

   pod 'AFNetworking'
   pod 'SDWebImage/GIF'
   pod 'MBProgressHUD'
   pod 'SVProgressHUD'
   pod 'Masonry'
   pod 'IQKeyboardManager'
   pod 'MJRefresh'
   pod 'SDWebImage'
   pod 'FLAnimatedImage'
   pod 'YBImageBrowser' 

  
 

end
