platform :ios, '9.0'

target 'StorageStarted' do
  pod 'AVOSCloud', '12.3.0'
  pod 'SDWebImage'
  pod 'SSZipArchive'
  pod 'GZIP', '~> 1.2'
  pod 'AFNetworking'
  pod 'SDCycleScrollView','>= 1.82'
end
